import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useEffect } from "react";
import ColorThief from "colorthief";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [rgb, setRgb] = React.useState([]);

  function getDominantColor(imageUrl, callback) {
    const img = document.createElement("IMG");
    const colorThief = new ColorThief();
    img.setAttribute("src", imageUrl);
    img.crossOrigin = "Anonymous";
    if (img.complete) {
      callback(colorThief.getColor(img));
    } else {
      img.addEventListener("load", function () {
        callback(colorThief.getColor(img));
      });
    }
  }

  React.useEffect(() => {
    getDominantColor(
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
      setRgb
    );
  }, []);

  useEffect(() => {
    console.log("xxx", rgb);
  }, [rgb]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            height: "50vh",
            width: "50vw",
            background: `linear-gradient(180deg,rgb(${rgb?.map(
              (v) => v + 30
            )}) 0%, rgb(${rgb?.map((v) => v - 30)}) 100%)`,
          }}
        ></div>
        {/* lighter */}
        <div
          style={{
            width: "100px",
            height: "100px",
            backgroundColor: `rgb(${rgb?.map((v) => v + 30)})`,
          }}
        ></div>

        <div
          style={{
            width: "100px",
            height: "100px",
            backgroundColor: `rgb(${rgb})`,
          }}
        ></div>

        {/* Darker */}
        <div
          style={{
            width: "100px",
            height: "100px",
            backgroundColor: `rgb(${rgb?.map((v) => v - 30)})`,
          }}
        ></div>
      </main>
    </>
  );
}
